// Code generated by protoc-gen-go. DO NOT EDIT.
// source: basepb.proto

package basepb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 基础结构，主要提供给tcp内部使用，目前客户端用不到
type Base struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Base) Reset()         { *m = Base{} }
func (m *Base) String() string { return proto.CompactTextString(m) }
func (*Base) ProtoMessage()    {}
func (*Base) Descriptor() ([]byte, []int) {
	return fileDescriptor_acce15d0fbf96fc9, []int{0}
}

func (m *Base) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Base.Unmarshal(m, b)
}
func (m *Base) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Base.Marshal(b, m, deterministic)
}
func (m *Base) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Base.Merge(m, src)
}
func (m *Base) XXX_Size() int {
	return xxx_messageInfo_Base.Size(m)
}
func (m *Base) XXX_DiscardUnknown() {
	xxx_messageInfo_Base.DiscardUnknown(m)
}

var xxx_messageInfo_Base proto.InternalMessageInfo

// rpc 无消息返回时可以返回这个值
type Base_Success struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Base_Success) Reset()         { *m = Base_Success{} }
func (m *Base_Success) String() string { return proto.CompactTextString(m) }
func (*Base_Success) ProtoMessage()    {}
func (*Base_Success) Descriptor() ([]byte, []int) {
	return fileDescriptor_acce15d0fbf96fc9, []int{0, 0}
}

func (m *Base_Success) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Base_Success.Unmarshal(m, b)
}
func (m *Base_Success) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Base_Success.Marshal(b, m, deterministic)
}
func (m *Base_Success) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Base_Success.Merge(m, src)
}
func (m *Base_Success) XXX_Size() int {
	return xxx_messageInfo_Base_Success.Size(m)
}
func (m *Base_Success) XXX_DiscardUnknown() {
	xxx_messageInfo_Base_Success.DiscardUnknown(m)
}

var xxx_messageInfo_Base_Success proto.InternalMessageInfo

// rpc 发生错误时可以返回这个值
type Base_Error struct {
	ErrorCode            int64    `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Fields               []string `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Base_Error) Reset()         { *m = Base_Error{} }
func (m *Base_Error) String() string { return proto.CompactTextString(m) }
func (*Base_Error) ProtoMessage()    {}
func (*Base_Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_acce15d0fbf96fc9, []int{0, 1}
}

func (m *Base_Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Base_Error.Unmarshal(m, b)
}
func (m *Base_Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Base_Error.Marshal(b, m, deterministic)
}
func (m *Base_Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Base_Error.Merge(m, src)
}
func (m *Base_Error) XXX_Size() int {
	return xxx_messageInfo_Base_Error.Size(m)
}
func (m *Base_Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Base_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Base_Error proto.InternalMessageInfo

func (m *Base_Error) GetErrorCode() int64 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *Base_Error) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *Base_Error) GetFields() []string {
	if m != nil {
		return m.Fields
	}
	return nil
}

func init() {
	proto.RegisterType((*Base)(nil), "basepb.base")
	proto.RegisterType((*Base_Success)(nil), "basepb.base.Success")
	proto.RegisterType((*Base_Error)(nil), "basepb.base.Error")
}

func init() {
	proto.RegisterFile("basepb.proto", fileDescriptor_acce15d0fbf96fc9)
}

var fileDescriptor_acce15d0fbf96fc9 = []byte{
	// 165 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x2c, 0x8e, 0xb1, 0x0a, 0xc2, 0x30,
	0x14, 0x45, 0xa9, 0xd5, 0x4a, 0x1e, 0x75, 0xc9, 0x20, 0xa1, 0x20, 0x14, 0x5d, 0x3a, 0x65, 0xf1,
	0x0f, 0x14, 0x47, 0x97, 0xfa, 0x01, 0xd2, 0x26, 0xcf, 0x12, 0x68, 0x78, 0x25, 0xcf, 0xf6, 0xfb,
	0xa5, 0x89, 0xdb, 0x3d, 0xe7, 0x2e, 0x07, 0xca, 0xbe, 0x63, 0x9c, 0x7a, 0x3d, 0x05, 0xfa, 0x92,
	0x2c, 0x12, 0x9d, 0x17, 0xd8, 0xae, 0xab, 0x12, 0xb0, 0x7f, 0xcd, 0xc6, 0x20, 0x73, 0x65, 0x60,
	0xf7, 0x08, 0x81, 0x82, 0x3c, 0x01, 0xe0, 0x3a, 0xde, 0x86, 0x2c, 0xaa, 0xac, 0xce, 0x9a, 0xbc,
	0x15, 0xd1, 0xdc, 0xc9, 0xa2, 0xbc, 0xc0, 0x21, 0xdd, 0x1e, 0x99, 0xbb, 0x01, 0xd5, 0xa6, 0xce,
	0x1a, 0xd1, 0x96, 0x51, 0x3e, 0x93, 0x93, 0x47, 0x28, 0x3e, 0x0e, 0x47, 0xcb, 0x2a, 0xaf, 0xf3,
	0x46, 0xb4, 0x7f, 0xba, 0x55, 0xa0, 0x0c, 0x79, 0xcd, 0x61, 0x76, 0x7a, 0xe8, 0x3c, 0x8e, 0x6e,
	0x41, 0x9d, 0x9a, 0xfa, 0x22, 0x26, 0x5e, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x70, 0x00, 0x2a,
	0x44, 0xb2, 0x00, 0x00, 0x00,
}
